sudo: required
language: generic
services:
    - docker

before_install:
    - docker build -t atishagusain/docker-react -f Dockerfile.dev .

script:
    - docker run script:
        - docker run -e CI=true atishagusain/docker-react npm run test -- --coverage
