language: generic
sudo: required
services:
    - docker

before_install:
    - docker build -t atisha/docker-react -f Dockerfile.dev .

script:
    - docker run script:
        - docker run -e CI=true atisha/docker-react npm run test 